---
title: "New_Barbera"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
library(mosaic)
library(caret)
library(httr)
library(jsonlite)
# library(RTwitterV2)
library(tweetscores)
library(rtweet)
library(tidyverse)
library(gridExtra)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```

```{r}
load("elite_info.RData")
elite_info
```

```{r, eval = F}
dime = read.csv("dime_recipients_1979_2022.csv")
```

```{r}
dime_22 = dime %>% filter(cycle == 2022) %>% 
  select(election, cycle, lname, fname, party,
         recipient.cfscore, contributor.cfscore, dwdime, dwnom1, dwnom2) 

names(dime)

# dime_22 <- dime_22[complete.cases(dime_22$fname, dime_22$lname), ]


dime_22[dime_22 == ""] <- NA
summary(dime_22)
dime_22 %>% filter(!is.na(lname)) %>% filter(lname == "biden")

dime_22$name <- paste(dime_22$fname, dime_22$lname)

dime_22 = dime_22 %>% distinct(name, .keep_all = TRUE)

dime_22 %>% filter(name == "joseph biden")

dime_22 %>% filter(lname == "craig")

dime_22 %>% filter(lname == "pelosi")
dime_22 %>% filter(lname == "biden")
```


```{r}
plot(density(dime_22$recipient.cfscore))
abline(v = -1, col = "red", lwd = 2)

plot(density(dime_22$contributor.cfscore, na.rm = T))
plot(density(dime_22$dwdime, na.rm = T))
```



```{r}
elite_ours <- compare %>% select(elite, gamma, new_gamma, yty_gamma)
elite_ours <- left_join(elite_ours, elite_info, by = join_by(elite == id_str))
elite_ours


# Remove the titles and convert the names to lowercase
elite_ours$Name <- elite_ours$name
elite_ours$name <- gsub("Rep\\.|Senator|Congresswoman|Congressman", "", elite_ours$name)
elite_ours$name <- tolower(elite_ours$name)

# Trim any leading or trailing spaces
elite_ours$name <- trimws(elite_ours$name)
elite_ours$name <- gsub("[^A-Za-z ]", "", elite_ours$name)

elite_ours <- elite_ours %>% 
  select(elite, gamma, new_gamma, yty_gamma, name, location, Name) %>% 
  mutate(name = ifelse(name == "joe biden", "joseph biden", name)) %>% 
  mutate(name = ifelse(name == "dan kildee", "daniel kildee", name)) %>% 
  mutate(name = ifelse(name == "tammy duckworth", "l tammy duckworth", name)) %>% 
  mutate(name = ifelse(name == "charles grassley", "charles grassley", name)) %>% 
  mutate(name = ifelse(name == "joe morelle", "joseph morelle", name))%>% 
  mutate(name = ifelse(name == "deb fischer", "debra fischer", name))%>% 
  mutate(name = ifelse(name == "brad schneider", "bradley schneider", name))%>% 
  mutate(name = ifelse(name == "ben cline", "benjamin cline", name))%>% 
  mutate(name = ifelse(name == "angie craig", "angela craig", name))%>% 
  mutate(name = ifelse(name == "pete stauber", "peter stauber", name))

```


```{r}
verify_data = left_join(elite_ours, dime_22 ,by = join_by(name == name))

verify_data_cc = cc(verify_data)
# verify_data_unmatch = verify_data %>% filter(is.na(lname))
# verify_data_unmatch = verify_data_unmatch[1:7]
# 
# verify_data_unmatch$last_name <- sub(".*\\s", "", verify_data_unmatch$name)
# verify_data_match <- left_join(verify_data_unmatch, dime_22, 
#                                by = join_by(last_name == lname)) %>% distinct(name.x, .keep_all = T)
# 
# verify_data_cc = rbind(cc(verify_data) %>% select(-c(name, lname)), verify_data_match %>% select(-c(name.x, name.y, last_name)))
# 
# cc(verify_data_cc)
```


```{r}
library(mice)

verify_data_cc <- cc(verify_data_cc)

plot(gamma~ recipient.cfscore, verify_data_cc, ylab = "Barbera's estimate")
plot(gamma~ contributor.cfscore, verify_data_cc)
plot(gamma~ dwdime, verify_data_cc)

plot(new_gamma~ recipient.cfscore, verify_data_cc, ylab = "Our estimate")
plot(new_gamma~ contributor.cfscore, verify_data_cc)
plot(new_gamma~ dwdime, verify_data_cc)

plot(yty_gamma~ recipient.cfscore, verify_data_cc)
plot(yty_gamma~ contributor.cfscore, verify_data_cc)
plot(yty_gamma~ dwdime, verify_data_cc)


plot(gamma~ new_gamma, verify_data_cc)

verify_data_cc %>% ggplot() + 
    geom_point(aes(x = new_gamma, y = gamma), col = 1, size = 0.3) + 
    geom_point(aes(x = new_gamma, y = recipient.cfscore), col = 2, size = 0.3)+
    geom_point(aes(x = new_gamma, y = contributor.cfscore), col = 3, size = 0.3)+
    geom_point(aes(x = new_gamma, y = dwdime), col = 4, size = 0.3)

elite_ours%>% ggplot() + 
    geom_point(aes(x = new_gamma, y = gamma), col = 1, size = 0.3)
```








